// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caeneflwritwknfdbjoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZW5lZmx3cml0d2tuZmRiam9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDgyNTYsImV4cCI6MjA1NzgyNDI1Nn0.aW2f7rbuHs5Mnvj7PDN-tF_kCXdapBQOFFyQH6C70vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);